// <auto-generated />
using System;
using BookstoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookstoreAPI.Migrations
{
    [DbContext(typeof(BookstoreDbContext))]
    [Migration("20260424185041_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BookstoreAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("Genre");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "David Thomas",
                            CreatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3758),
                            Description = "Your journey to mastery.",
                            Genre = "Technology",
                            ISBN = "978-0135957059",
                            Price = 49.99m,
                            PublishedDate = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 25,
                            Title = "The Pragmatic Programmer",
                            UpdatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3760)
                        },
                        new
                        {
                            Id = 2,
                            Author = "Robert C. Martin",
                            CreatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3765),
                            Description = "A handbook of agile software craftsmanship.",
                            Genre = "Technology",
                            ISBN = "978-0132350884",
                            Price = 39.99m,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 18,
                            Title = "Clean Code",
                            UpdatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3765)
                        },
                        new
                        {
                            Id = 3,
                            Author = "Frank Herbert",
                            CreatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3768),
                            Description = "A science fiction masterpiece.",
                            Genre = "Science Fiction",
                            ISBN = "978-0441013593",
                            Price = 14.99m,
                            PublishedDate = new DateTime(1965, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StockQuantity = 42,
                            Title = "Dune",
                            UpdatedAt = new DateTime(2026, 4, 24, 18, 50, 41, 476, DateTimeKind.Utc).AddTicks(3768)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
